Make sbt 1.1.0 the minimum required version
sbt 1.0.x is not supported, throwing the following on startup:

```
[error] java.lang.NoSuchMethodError: sbt.package$.sbtSlashSyntaxRichConfiguration(Lsbt/librarymanagement/Configuration;)Lsbt/SlashSyntax$RichConfiguration;
```

This corrects the documentation and reqs check to specify 1.1.0 as the
minimum required sbt version.